version: '3.7'

services:

    jigsaw:
        container_name: jigsaw
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - '../../:/jigsaw'
            - '/jigsaw/node_modules'
        ports:
            - '50001:50000'
        environment: 
            - NODE_ENV=prod
            - PORT=50001
        tty: true
        stdin_open: true

    # jigsaw-frontend:
    #     container_name: jigsaw-frontend
    #     build:
    #         context: ../../frontend/
    #         dockerfile: Dockerfile
    #     volumes:
    #         - '../../frontend:/jigsaw-frontend'
    #         - '/jigsaw-frontend/node_modules'
    #     ports:
    #         - '30001:30000'
    #     environment:
    #         - NODE_ENV=prod
    #     tty: true
    #     stdin_open: true

    # nginx:
    #     container_name: nginx
    #     build:
    #         context: ../../frontend/nginx
    #         dockerfile: Dockerfile
