version: '3.7'

services:

    jigsaw:
        container_name: jigsaw
        build:
            context: ../../
            dockerfile: Dockerfile
        volumes:
            - '../../:/jigsaw'
            - '/jigsaw/node_modules'
        ports:
            - '8080'
        environment: 
            - NODE_ENV=dev
            - PORT=8080
        tty: true
        stdin_open: true
